apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: admin-svc-hpa
  namespace: adminsvc-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: admin-svc
  minReplicas: 2
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pathqa-svc-hpa
  namespace: pathqasvc-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pathqa-svc
  minReplicas: 2
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

